name: shell command

on:
  - push

jobs:
 run-shel-commands:
   runs-on: ubuntu-latest
   steps:
   - name: echo string
     run: echo "peace-be"
   - name: multi line string
     run: |
       pwd
       node -v
       ls -a
   - name: python command 
     run:
       import platform
       print(platform.processor())
     shell: python
